name: test-windows
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: "Dependency: Install Golang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: "Dependency: Install Scoop+Make+NodeJS"
        shell: pwsh
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
          scoop install make@4.3 nodejs@16.17.1

      - name: "Checkout Repo"
        uses: actions/checkout@v3

      - name: "Setup caching"
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Build CLI"
        shell: pwsh
        run: make build-cli-windows-amd ARCH=amd64

      - name: "Make Packages"
        shell: pwsh
        run: |
          make init-package build-examples ARCH=amd64
          ls .\build
          exit

      - name: "Run Tests"
        shell: pwsh
        run: |
          make test-e2e ARCH=amd64 -e RUN_CLUSTER_TESTS=false

      - name: "Cleanup"
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force .\build\
